export const searchIndex = [
  { type: "Tool", title: "JSON Formatter & Validator", description: "Format and validate JSON locally.", href: "/tools/json-formatter", keywords: "json developer format validate" },
  { type: "Tool", title: "Base64 Encoder / Decoder", description: "Encode and decode Base64 locally.", href: "/tools/base64", keywords: "base64 encode decode developer" },
  { type: "Tool", title: "JWT Decoder", description: "Decode JWT headers and payloads locally.", href: "/tools/jwt-decoder", keywords: "jwt token developer auth decode" },
  { type: "Tool", title: "UUID Generator", description: "Generate UUIDs locally.", href: "/tools/uuid-generator", keywords: "uuid id generator developer" },
  { type: "Tool", title: "URL Encoder / Decoder", description: "Encode and decode URL components.", href: "/tools/url-encoder", keywords: "url encode decode developer" },
  { type: "Tool", title: "Unix Timestamp Converter", description: "Convert Unix timestamps and ISO dates.", href: "/tools/timestamp", keywords: "timestamp unix date time developer" },
  { type: "Tool", title: "SEO & Social Preview", description: "Preview titles, descriptions, URLs and social cards.", href: "/tools/seo-preview", keywords: "seo metadata social og preview" },
  { type: "Tool", title: "Next.js Meta Generator", description: "Generate App Router metadata objects.", href: "/tools/meta-tag-generator", keywords: "nextjs metadata meta tags canonical open graph" },
  { type: "Tool", title: "Image Compressor", description: "Compress images to WebP in the browser.", href: "/tools/image-compressor", keywords: "image compress webp creator" },
  { type: "Tool", title: "QR Code Generator", description: "Generate downloadable QR codes for URLs and text.", href: "/tools/qr-generator", keywords: "qr qrcode code barcode" },
  { type: "Project", title: "HR-BOT", description: "Highrise automation and music bot.", href: "/projects/hr-bot", keywords: "python highrise bot docker coolify" },
  { type: "Project", title: "Discord Bot", description: "Discord utilities and management automation.", href: "/projects/discord-bot", keywords: "discord javascript automation bot" },
  { type: "Project", title: "Chat Platform", description: "Real-time communication experiment.", href: "/projects/chat-platform", keywords: "node websocket realtime chat" },
  { type: "Blog", title: "Building SLOW.DEV Into a Personal Platform", description: "Why SLOW.DEV is becoming more than a portfolio.", href: "/blog/building-slow-dev-into-a-personal-platform", keywords: "platform portfolio creator tools" },
  { type: "Blog", title: "Why SLOW Tools Are Local-First", description: "Fast, private browser-first developer tools.", href: "/blog/designing-local-first-developer-tools", keywords: "local first privacy browser tools" },
  { type: "Page", title: "Services", description: "Web development, automation, AI, performance and SEO.", href: "/services", keywords: "services web ai automation seo performance" },
  { type: "Page", title: "Creator Hub", description: "Gaming, YouTube, Kick and Discord.", href: "/creator", keywords: "creator gaming youtube kick discord stream" },
  { type: "Page", title: "Gaming", description: "Streams, games and community.", href: "/gaming", keywords: "gaming stream games kick community" },
  { type: "Page", title: "Now", description: "What SLOW is working on now.", href: "/now", keywords: "now current building" },
  { type: "Page", title: "Docs", description: "Documentation and developer notes for SLOW.DEV.", href: "/docs", keywords: "docs documentation developer guide" },
  { type: "Page", title: "Status", description: "SLOW.DEV service status and health.", href: "/status", keywords: "status uptime health" },
  { type: "Page", title: "Contact", description: "Start a project with SLOW.", href: "/contact", keywords: "contact project hire work" },
] as const;
